### PR TITLE
Feature/433 dynamic types support

### PR DESCRIPTION
**Pull request by martin-zemek**

### CODE REVIEW

**Comment by turlyalz** [comment]
doens't work for me 
image

**Comment by davidnich** [comment]
> doens't work for me
@turlyalz does it only happen when the IDE is not connected to Qorus?  I didn't test that scenario

**Comment by martin-zemek** [comment]
yes, you need to be connected to Qorus

**Comment by davidnich** [comment]
@martin-zemek also the `Create new` button doesn't work - the fields on the form are not cleared

**Comment by turlyalz** [comment]
> yes, you need to be connected to Qorus

doesn' t work even when I'm connected

**Comment by Foxhoundn** [comment]
> @martin-zemek also the `Create new` button doesn't work - the fields on the form are not cleared

that's on me, that's frontend

**Comment by davidnich** [comment]
@Foxhoundn @turlyalz it's working for me now - the reset issues have been fixed

**Pull request merged**
